version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: lab6-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: lab6db
    ports:
      - "5432:5432"
    networks:
      - lab6-network

  app:
    build: .
    container_name: lab6-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://lab6-postgres:5432/lab6db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - lab6-network

networks:
  lab6-network:
